### PR TITLE
Avoid empty sequences being opened

### LINKED ISSUE #30: Empty sequnce possible
Empty sequences can be created and only get filled with at least one slide in the edit view. that means if a teacher never saves the sequence an empty sequnce can be shared

### PR DESCRIPTION
**Pull request by c0derMo**
Fixes #30

### CODE REVIEW

**Review by ProgramPhoenix — APPROVED** [review]

**Comment by c0derMo** [comment]
Build currently fails because of an update of the H5P-Library, which partially breaks our code - fixes are being worked on on the `h5p-improvement` branch, moving this to a draft until that's done

**Review by ProgramPhoenix — APPROVED** [review]

**Comment by Kr0nox** [comment]
I feal like a better fix would be to add an empty slide when creating it. This could cause confusion with the user, since the sequence exists

**Comment by ProgramPhoenix** [comment]
i would expect an sequence, that i created and never edited to be empty, and also if i delete all slides i have the same problem again.

**Comment by Kr0nox** [comment]
Its not possible to delete all slides. When you first open the slide in the editor, there it gets created with one slide. It might be really confusing for students to get a code from a teacher, for it to then say it does not exists

**Comment by ProgramPhoenix** [comment]
but what expected the teacher to happen when he gives an code to the students from a slide he never even open?

I tried to delete all slides and its correct i cant delete all, but i can write a request, that does so. Since we would need to enforce this also in the sequencecontroller in the save function. 

i think throwing an error is okay since we can display the correct message in the upcoming error improvement.

**Comment by Kr0nox** [comment]
> but what expected the teacher to happen when he gives an code to the students from a slide he never even open?

But if he opens it and then closes without saving, then he would expect there to be a slide

**Comment by ProgramPhoenix** [comment]
> But if he opens it and then closes without saving, then he would expect there to be a slide

we even have a warning that if he leaves the site, unsaved changes will be lost. so i would expect nothing in the sequence

**Comment by c0derMo** [comment]
I do agree that slides which were never saved, or empty sequences shouldn't be opened at all, since it doesn't really make sense to me, even if it's an sequence with a single empty slide, to be opened

**Comment by Kr0nox** [comment]
> I do agree that slides which were never saved, or empty sequences shouldn't be opened at all, since it doesn't really make sense to me, even if it's an sequence with a single empty slide, to be opened

Then we  should also prohibt sharing them in the first place

**Comment by c0derMo** [comment]
> Then we should also prohibt sharing them in the first place

That's fair, we could just hide the "Share with Students" tab inside the options if it's empty

**Comment by Kr0nox** [comment]
> That's fair, we could just hide the "Share with Students" tab inside the options if it's empty

either that or write a message there that empty sequences should not be shared to not confuse the teachers

**Review by Kr0nox — APPROVED** [review]

**Pull request merged**
