### PR TITLE
Improving Accountcontroller (Empty Fields and more)

### LINKED ISSUE #17: Problems with ensureAdminAccount
When the admin deletes himself and someone takes username admin, both the username admin and the actual admin cannt login. We discussed this already. just opening this, so we dont forget about this.

### LINKED ISSUE #22: Empty Usernames are allowed in the Backend
In the recent Account view pr(#18) we had discussions about empty fields and allowing these. We should check in the backend for empty fields and throw an error

### PR DESCRIPTION
**Pull request by ProgramPhoenix**
Adding a test for empty fields or against the default fields, that an automated created admin has. Also checking that a password is longer than 6 characters. Closing #22 and #17

### CODE REVIEW

**Comment by ProgramPhoenix** [comment]
Just a thought, if we have the default admin created and the admin just wants to change the mail not the name, he gets an error, should we allow that?

**Comment by ProgramPhoenix** [comment]
Ok, short status updated, in the same save request a user will be promoted to admin, he can bypass all further checks, except the check for emptiness. 
An example: admin with name max mustermann promotes erika mustermann to an admin in the same edit he can change her name to admin. vice versa: max mustermann demotes erika mustermann to a normal teacher he wont be able to set her name to admin.
I dont see a current option for making the bypass depends from the Editors userclass. Any thoughts @c0derMo @Kr0nox ?

**Comment by c0derMo** [comment]
I think one way would be not only checking userclass that's being saved, but the userclass of the user that's being edited by comparing to `dbuser` - e.g. an admin can always set name & email to whatever, of another admin or himself

**Comment by ProgramPhoenix** [comment]
as long as he edits another admin, we are always sending the userclass along, he just can't not bypass the checks for normal users. But i am adding the check you mentioned soon, because if the admin edits himself in the account view he can not bypass the checks for himself

**Review by c0derMo — APPROVED** [review]

**Review by Kr0nox — APPROVED** [review]

**Pull request merged**
